
export const PROFILE_START = 'PROFILE_START';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAIL = 'PROFILE_FAIL';

export const ADMISSION_START = 'ADMISSION_START';
export const ADMISSION_SUCCESS = 'ADMISSION_SUCCESS';
export const ADMISSION_FAIL = 'ADMISSION_FAIL';